CREATE DATABASE IF NOT EXISTS crsp;
DROP TABLE IF EXISTS crsp.daily_stock_price_old;

CREATE TABLE crsp.daily_stock_price_old (
    PERMNO      UInt32,
    date        Date32,
    NAMEENDT    Nullable(Date32),
    SHRCD       Nullable(Int32),
    EXCHCD      Nullable(Int32),
    SICCD       Nullable(String),
    NCUSIP      Nullable(String),
    TICKER      LowCardinality(String),
    COMNAM      Nullable(String),
    SHRCLS      LowCardinality(String),
    TSYMBOL     LowCardinality(String),
    NAICS       Nullable(Int32),
    PRIMEXCH    LowCardinality(String),
    TRDSTAT     LowCardinality(String),
    SECSTAT     LowCardinality(String),
    PERMCO      Nullable(Int32),
    ISSUNO      Nullable(Int32),
    HEXCD       Nullable(Int32),
    HSICCD      Nullable(Int32),
    CUSIP       Nullable(String),
    DCLRDT      Nullable(Date32),
    DLAMT       Nullable(Float64),
    DLPDT       Nullable(Date32),
    DLSTCD      Nullable(Int32),
    NEXTDT      Nullable(Date32),
    PAYDT       Nullable(Date32),
    RCRDDT      Nullable(Date32),
    SHRFLG      Nullable(Int32),
    HSICMG      Nullable(Int32),
    HSICIG      Nullable(Int32),
    DISTCD      Nullable(Int32),
    DIVAMT      Nullable(Float64),
    FACPR       Nullable(Float64),
    FACSHR      Nullable(Float64),
    ACPERM      Nullable(Int32),
    ACCOMP      Nullable(Int32),
    SHRENDDT    Nullable(Date32),
    NWPERM      Nullable(Int32),
    DLRETX      Nullable(String),
    DLPRC       Nullable(Float64),
    DLRET       Nullable(String),
    TRTSCD      Nullable(Int32),
    NMSIND      Nullable(Int32),
    MMCNT       Nullable(Int32),
    NSDINX      Nullable(Float64),
    BIDLO       Nullable(Float64),
    ASKHI       Nullable(Float64),
    PRC         Nullable(Float64),
    VOL         Nullable(Int64),
    RET         Nullable(String),
    BID         Nullable(Float64),
    ASK         Nullable(Float64),
    SHROUT      Nullable(Int64),
    CFACPR      Nullable(Float64),
    CFACSHR     Nullable(Float64),
    OPENPRC     Nullable(Float64),
    NUMTRD      Nullable(Int64),
    RETX        Nullable(String),
    vwretd      Nullable(Float64),
    vwretx      Nullable(Float64),
    ewretd      Nullable(Float64),
    ewretx      Nullable(Float64),
    sprtrn      Nullable(Float64)
)
ENGINE = MergeTree()
ORDER BY (PERMNO, date);
