CREATE DATABASE IF NOT EXISTS crsp;
DROP TABLE IF EXISTS crsp.sp500_constituents;

CREATE TABLE crsp.sp500_constituents (
    INDNO               UInt32,
    MbrStartDt          Date32,
    MbrEndDt            Nullable(Date32),
    PERMNO              UInt32,
    HdrCUSIP            String,
    PERMCO              Nullable(Int32),
    SICCD               Nullable(Int32),
    CUSIP               String,
    Ticker              LowCardinality(String),
    ShareType           LowCardinality(String),
    SecurityType        LowCardinality(String),
    SecuritySubType     LowCardinality(String),
    USIncFlg            LowCardinality(String),
    IssuerType          LowCardinality(String),
    PrimaryExch         LowCardinality(String),
    ConditionalType     LowCardinality(String),
    TradingStatusFlg    LowCardinality(String),
    DlyCalDt            Date32,
    DlyPrc              Nullable(Float64),
    DlyPrcFlg           LowCardinality(String),
    DlyCap              Nullable(Float64),
    DlyCapFlg           LowCardinality(String),
    DlyRet              Nullable(Float64),
    DlyRetx             Nullable(Float64),
    DlyRetMissFlg       LowCardinality(String),
    DlyRetDurFlg        LowCardinality(String),
    DlyOrdDivAmt        Nullable(Float64),
    DlyNonOrdDivAmt     Nullable(Float64),
    DlyFacPrc           Nullable(Float64),
    DlyDistRetFlg       LowCardinality(String),
    DlyVol              Nullable(Int64),
    DlyClose            Nullable(Float64),
    DlyLow              Nullable(Float64),
    DlyHigh             Nullable(Float64),
    DlyBid              Nullable(Float64),
    DlyAsk              Nullable(Float64),
    DlyOpen             Nullable(Float64),
    DlyNumTrd           Nullable(Int64),
    DlyMMCnt            Nullable(Int32),
    DlyCumFacPr         Nullable(Float64),
    DlyCumFacShr        Nullable(Float64),
    ShrOut              Nullable(Int64)
)
ENGINE = MergeTree()
ORDER BY (PERMNO, DlyCalDt);
