CREATE DATABASE IF NOT EXISTS crsp;
DROP TABLE IF EXISTS crsp.compustat_link;

CREATE TABLE crsp.compustat_link (
    gvkey           String,
    conm            Nullable(String),
    tic             LowCardinality(String),
    cusip           Nullable(String),
    cik             Nullable(Int64),
    sic             Nullable(Int32),
    naics           Nullable(Int32),
    LINKPRIM        LowCardinality(String),
    LIID            LowCardinality(String),
    LINKTYPE        LowCardinality(String),
    LPERMNO         Int32,
    LPERMCO         Nullable(Int32),
    LINKDT          Nullable(Date32),
    LINKENDDT       Nullable(String),
    EIN             Nullable(String),
    COSTAT          LowCardinality(String),
    DLRSN           LowCardinality(String),
    PRIUSA          Nullable(String),
    PRICAN          Nullable(String),
    PRIROW          Nullable(String),
    IDBFLAG         LowCardinality(String),
    FIC             LowCardinality(String),
    LOC             LowCardinality(String),
    INCORP          LowCardinality(String),
    STATE           LowCardinality(String),
    COUNTY          Nullable(String),
    CITY            Nullable(String),
    CONML           Nullable(String),
    WEBURL          Nullable(String),
    PHONE           Nullable(String),
    FAX             Nullable(String),
    ADD1            Nullable(String),
    ADD2            Nullable(String),
    ADD3            Nullable(String),
    ADD4            Nullable(String),
    ADDZIP          Nullable(String),
    BUSDESC         Nullable(String),
    ipodate         Nullable(Date32),
    dldte           Nullable(Date32),
    STKO            Nullable(Int32),
    FYRC            Nullable(Int32),
    GSECTOR         Nullable(Int32),
    GGROUP          Nullable(Int32),
    GIND            Nullable(Int32),
    GSUBIND         Nullable(Int32),
    SPCINDCD        Nullable(Int32),
    SPCSECCD        Nullable(Int32)
)
ENGINE = MergeTree()
ORDER BY (gvkey, LPERMNO);
