-- Compustat Financial Ratios (finratio)
-- Source: WRDS wrdsapps_finratio.firm_ratio (joined with CRSP permno)
-- ~3.07M rows, 1969-present, monthly snapshots per gvkey
-- divyield is stored as String because WRDS exports include '%' suffix (e.g., ".769%")

CREATE TABLE IF NOT EXISTS compustat.finratio (
    gvkey String,
    permno Nullable(Int64),
    adate Nullable(Date32),
    qdate Nullable(Date32),
    public_date Date32,
    CAPEI Nullable(Float64),
    bm Nullable(Float64),
    evm Nullable(Float64),
    pe_op_basic Nullable(Float64),
    pe_op_dil Nullable(Float64),
    pe_exi Nullable(Float64),
    pe_inc Nullable(Float64),
    ps Nullable(Float64),
    pcf Nullable(Float64),
    dpr Nullable(Float64),
    npm Nullable(Float64),
    opmbd Nullable(Float64),
    opmad Nullable(Float64),
    gpm Nullable(Float64),
    ptpm Nullable(Float64),
    cfm Nullable(Float64),
    roa Nullable(Float64),
    roe Nullable(Float64),
    roce Nullable(Float64),
    efftax Nullable(Float64),
    aftret_eq Nullable(Float64),
    aftret_invcapx Nullable(Float64),
    aftret_equity Nullable(Float64),
    pretret_noa Nullable(Float64),
    pretret_earnat Nullable(Float64),
    GProf Nullable(Float64),
    equity_invcap Nullable(Float64),
    debt_invcap Nullable(Float64),
    totdebt_invcap Nullable(Float64),
    capital_ratio Nullable(Float64),
    int_debt Nullable(Float64),
    int_totdebt Nullable(Float64),
    cash_lt Nullable(Float64),
    invt_act Nullable(Float64),
    rect_act Nullable(Float64),
    debt_at Nullable(Float64),
    debt_ebitda Nullable(Float64),
    short_debt Nullable(Float64),
    curr_debt Nullable(Float64),
    lt_debt Nullable(Float64),
    profit_lct Nullable(Float64),
    ocf_lct Nullable(Float64),
    cash_debt Nullable(Float64),
    fcf_ocf Nullable(Float64),
    lt_ppent Nullable(Float64),
    dltt_be Nullable(Float64),
    debt_assets Nullable(Float64),
    debt_capital Nullable(Float64),
    de_ratio Nullable(Float64),
    intcov Nullable(Float64),
    intcov_ratio Nullable(Float64),
    cash_ratio Nullable(Float64),
    quick_ratio Nullable(Float64),
    curr_ratio Nullable(Float64),
    cash_conversion Nullable(Float64),
    inv_turn Nullable(Float64),
    at_turn Nullable(Float64),
    rect_turn Nullable(Float64),
    pay_turn Nullable(Float64),
    sale_invcap Nullable(Float64),
    sale_equity Nullable(Float64),
    sale_nwc Nullable(Float64),
    rd_sale Nullable(Float64),
    adv_sale Nullable(Float64),
    staff_sale Nullable(Float64),
    accrual Nullable(Float64),
    ptb Nullable(Float64),
    PEG_trailing Nullable(Float64),
    divyield Nullable(String),
    Ticker Nullable(String),
    CUSIP Nullable(String)
) ENGINE = MergeTree()
ORDER BY (gvkey, public_date);
